version: '2.4'

services:
  postgres:
    image: library/postgres:latest
    volumes:
      - ./docker-postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD="trust"
      - POSTGRES_PASSWORD=password
    container_name: keycloak-postgres

  keycloak:
    image: quay.io/keycloak/keycloak:12.0.4
    #volumes:
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=keycloak-postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_SCHEMA=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
    container_name: keycloak


